export const questions = [
  {
    id: "q1",
    question: "What does HTML stand for?",
    type: "radio",
    choices: {
      a: "Hyper Text Markup Language",
      b: "High Tech Modern Language",
      c: "Home Tool Markup Language",
      d: "Hyperlinks and Text Markup Language",
    },
    answer: "a",
  },
  {
    id: "q2",
    question:
      "Which of the following are JavaScript frameworks? (Select all that apply)",
    type: "checkbox",
    choices: {
      a: "React",
      b: "Vue",
      c: "Angular",
      d: "Python",
    },
    answer: ["a", "b", "c"],
  },
  {
    id: "q3",
    question: "Is CSS used for styling web pages?",
    type: "truefalse",
    choices: {
      true: "True",
      false: "False",
    },
    answer: "true",
  },
  {
    id: "q4",
    question: "What is the primary purpose of Git?",
    type: "radio",
    choices: {
      a: "Version control",
      b: "Database management",
      c: "Web server",
      d: "Text editing",
    },
    answer: "a",
  },
  {
    id: "q5",
    question: "Which of these are popular databases? (Select all that apply)",
    type: "checkbox",
    choices: {
      a: "MongoDB",
      b: "PostgreSQL",
      c: "MySQL",
      d: "Excel",
    },
    answer: ["a", "b", "c"],
  },
  {
    id: "q6",
    type: "multiple",
    question: "Which keyword defines a function in Python?",
    choices: {
      A: "func",
      B: "function",
      C: "define",
      D: "def",
    },
    answer: "D",
  },
  {
    id: "q7",
    type: "multiple",
    question: "What does OOP stand for?",
    choices: {
      A: "Object Oriented Programming",
      B: "Open Object Protocol",
      C: "Operational Object Process",
      D: "Ordered Output Program",
    },
    answer: "A",
  },
  {
    id: "q8",
    type: "multiple",
    question: "Which loop is guaranteed to execute at least once?",
    choices: {
      A: "for",
      B: "while",
      C: "do-while",
      D: "foreach",
    },
    answer: "C",
  },
  {
    id: "q9",
    type: "multiple",
    question: "Which symbol is used for equality comparison in most languages?",
    choices: {
      A: "=",
      B: "==",
      C: "===",
      D: "!=",
    },
    answer: "B",
  },
  {
    id: "q10",
    type: "multiple",
    question: "What does IDE stand for?",
    choices: {
      A: "Integrated Development Environment",
      B: "Internal Design Engine",
      C: "Integrated Debug Editor",
      D: "Independent Development Environment",
    },
    answer: "A",
  },
  {
    id: "q11",
    type: "checkbox",
    question: "Which data structures use FIFO and LIFO?",
    choices: {
      A: "Stack",
      B: "Queue",
      C: "Array",
      D: "Tree",
    },
    answer: ["B", "C"],
  },
  {
    id: "q12",
    type: "multiple",
    question: "Which keyword is used to create a class in Python?",
    choices: {
      A: "object",
      B: "class",
      C: "struct",
      D: "define",
    },
    answer: "B",
  },
  {
    id: "q13",
    type: "multiple",
    question: "Which operator is used for logical AND?",
    choices: {
      A: "&",
      B: "&&",
      C: "|",
      D: "!",
    },
    answer: "B",
  },
];
